routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FeedbackController;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CommentController;
use Illuminate\Support\Facades\Auth;
use App\Models\Product;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    // $products = Product::all();
    $products = Product::with('feedbacks.comments')->get();
    // dd($products);
    return view('welcome', compact('products'));
});
Route::get('tiny', function(){
    return view('tiny');
});
// Route::get('/', [HomeController::class, 'index']);
Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function() {

    Route::resource('roles', RoleController::class);

    Route::resource('users', UserController::class);
    Route::post('/users/{user}/toggle-status', [UserController::class, 'toggleStatus'])->name('users.toggle-status');

    Route::resource('products', ProductController::class);

    Route::resource('feedbacks', FeedbackController::class);
    Route::post('/feedback/{feedback}/toggle-comments', [FeedbackController::class, 'toggleComments'])->name('feedback.toggle-comments');
    Route::post('/feedback/{feedback}/vote', [FeedbackController::class, 'vote'])->name('feedback.vote');
    Route::post('/feedback/{feedback}/comments', [CommentController::class, 'store'])->name('comments.store');

    Route::resource('categories', CategoryController::class);
});

app/Models/Feedback.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Feedback extends Model
{
    use HasFactory;
    protected $fillable = ['user_id', 'title', 'description', 'category_id', 'vote_count','product_id','comments_enabled'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function votes()
    {
        return $this->hasMany(Vote::class);
    }

}

app/Http/Controllers/FeedbackController.php
<?php

namespace App\Http\Controllers;

use App\Models\Feedback;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Models\Vote;
use Illuminate\Validation\ValidationException;
class FeedbackController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        // $feedbacks
        // $feedbacks = Feedback::with('user', 'category', 'comments')->paginate(10);
        $feedbacks = Feedback::select('id', 'title', 'user_id', 'category_id','vote_count','comments_enabled') // Specify columns from the feedbacks table
            ->with([
                'user:id,name', // Specify columns from the users table (id and name)
                'category:id,name', // Specify columns from the categories table (id and name)
                'comments:feedback_id,content' // Specify columns from the comments table (feedback_id and comment_content)
            ])->paginate(10);
        return view('feedback.index', compact('feedbacks'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories = Category::all();
        return view('feedback.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|string|max:255',
            'description' => 'required|string',
            'product_id' => 'required',
            'category_id' => 'required|exists:categories,id',
        ]);
        $existingFeedback = Feedback::where('user_id', auth()->user()->id)
        ->where('category_id', $request->input('category_id'))->first();

        // If a duplicate feedback entry exists, throw a validation exception
        if ($existingFeedback) {
            throw ValidationException::withMessages([
                'category_id' => ['You have already submitted feedback for this category.']
            ]);
        }

        $feedback = Feedback::create([
            'title' => $request->input('title'),
            'description' => $request->input('description'),
            'user_id' => auth()->user()->id, 
            'category_id' => $request->input('category_id'),
            'product_id' => $request->input('product_id'),
            'vote_count' => 0, // Default vote count
        ]); 
        // Redirect back with a success message
        return redirect()->route('products.index')->with('success', 'Feedback submitted successfully!');
    }

    /**
     * Display the specified resource.
     */
    public function show(Feedback $feedback)
    {
        return view('feedback.show', compact('feedback'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Feedback $feedback)
    {
        $categories = Category::all();
        return view('feedback.edit', compact('feedback','categories'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required|max:255',
            'description' => 'required',
            'category_id' => 'required|exists:categories,id',
        ]);

        $feedback = Feedback::find($id);
        // Check if the feedback record exists
        if (!$feedback) {
            return back()->with('error' , 'Feedback not found');
        }
        // Update the feedback record with the validated data
        $feedback->update($request->all());

        return redirect()->route('feedbacks.index')->with('success', 'Feedback updatted successfully!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Feedback $feedback)
    {
        $feedback->delete();
        return back()->with('success', 'Feedback deleted successfully!');
    }

    public function vote(Request $request, $feedbackId)
    {
        $feedback = Feedback::findOrFail($feedbackId);

        // Check if the user has already voted for this feedback
        if ($feedback->votes()->where('user_id', auth()->user()->id)->exists()) {
            // Unvote if already voted
            $feedback->votes()->where('user_id', auth()->user()->id)->delete();
            $feedback->decrement('vote_count'); // Decrement the vote count
        } else {
            // Vote if not already voted
            Vote::create([
                'user_id' => auth()->user()->id,
                'feedback_id' => $feedback->id,
            ]);
            $feedback->increment('vote_count'); // Increment the vote count
        }
        return back()->with('success', 'Vote updated successfully');
    }
    public function toggleComments(Request $request, Feedback $feedback)
    {
        $feedback->update([
            'comments_enabled' => !$feedback->comments_enabled,
        ]);
        return redirect()->back()->with('success', 'Comments status updated successfully.');
    }
}

resources/views/feedback/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Feedback</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('feedbacks.index') }}"> Back </a>
            </div>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> Something went wrong.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div class="col-6">
            <form method="post" action="{{ route('feedbacks.store') }}">
                @csrf
                <div class="mb-3">
                    <label for="title" class="form-label">Title</label>
                    <input type="text" class="form-control" id="title" name="title" required>
                </div>
                <div class="mb-3">
                    <label for="description" class="form-label">Description</label>
                    <textarea class="form-control" id="description" name="description" rows="3" required></textarea>
                </div>
                <div class="mb-3">
                    <label for="category" class="form-label">Category</label>
                    <select class="form-select" id="category" name="category_id" required>
                        @foreach($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

@endsection

resources/views/feedback/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Feedback</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('feedbacks.index') }}"> Back </a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> Something went wrong.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    {{-- @dd($feedback->category_id) --}}
    <form action="{{ route('feedbacks.update',$feedback->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Title:</strong>
                    <input type="text" name="name" value="{{ $feedback->title }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Description:</strong>
                    <textarea class="form-control" style="height:150px" name="description" placeholder="Description">{{ $feedback->description }}</textarea>
                </div>
            </div>
            <div class="mb-3">
                <label for="category" class="form-label">Category</label>
                <select class="form-select" id="category" name="category_id" required>
                    @foreach($categories as $category)
                        <option value="{{ $category->id }}" {{ $feedback->category_id == $category->id ? 'selected' : '' }}>
                            {{ $category->name }}
                        </option>
                    @endforeach
                </select>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 mt-4">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
		</div>
    </form>

{{-- 
<div class="container">
    <h2>Edit Feedback</h2>
    <form method="post" action="{{ route('feedback.update', $feedback->id) }}">
        @csrf
        @method('PUT')
        <div class="mb-3">
            <label for="title" class="form-label">Title</label>
            <input type="text" class="form-control" id="title" name="title" value="{{ $feedback->title }}" required>
        </div>
        <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <textarea class="form-control" id="description" name="description" rows="3" required>{{ $feedback->description }}</textarea>
        </div>
        <div class="mb-3">
            <label for="category" class="form-label">Category</label>
            <select class="form-select" id="category" name="category_id" required>
                @foreach($categories as $category)
                    <option value="{{ $category->id }}" {{ $feedback->category_id == $category->id ? 'selected' : '' }}>
                        {{ $category->name }}
                    </option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>
--}}
@endsection

resources/views/feedback/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">   
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Feedbacks</h2>
            </div>
            <div class="pull-right">
                @can('product-create')
                <a class="btn btn-success" href="{{ route('feedbacks.create') }}"> Create New Feedback </a>
                @endcan
            </div>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Title</th>
            <th width="100px">Vote Count</th>
            <th>User Name</th>
            @if(Auth::user()->role == 'admin')
            <th width="170px">Comments</th>
            @endif
            <th width="280px">Action</th>
        </tr>
        @foreach ($feedbacks as $feedback)
            {{-- @dd($feedback->user->name) --}}
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $feedback->title }}</td>
                <td>{{ $feedback->vote_count }}</td>
                <td>{{ $feedback->user->name }}</td>
                @if(Auth::user()->role == 'admin')
                <td class="d-flex justify-content-around">
                    <span>
                        {{ $feedback->comments_enabled ? 'Enabled' : 'Disabled' }}
                    </span>
                    {{-- Toggle Comments Button --}}
                    <form method="post" action="{{ route('feedback.toggle-comments', $feedback->id) }}">
                        @csrf
                        <button type="submit" class="btn btn-info pull-right">Toggle it</button>
                    </form>
                </td>
                @endif
                <td>
                    <form action="{{ route('feedbacks.destroy',$feedback->id) }}" method="POST">
                        <a class="btn btn-info" href="{{ route('feedbacks.show',$feedback->id) }}">Detail</a>
                        @if(Auth::user()->role == 'admin' || Auth::user()->id==$feedback->user_id)
                            <a class="btn btn-primary" href="{{ route('feedbacks.edit',$feedback->id) }}">Edit</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        @endif
                    </form>
                    
                </td>
            </tr>
        @endforeach
    </table>

    {!! $feedbacks->links() !!}

@endsection
{{-- 
@extends('layouts.app')

@section('content')
<div class="container">
    <h2>Feedback List</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Category</th>
                <th>Vote Count</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach($feedbacks as $feedback)
                <tr>
                    <td>{{ $feedback->title }}</td>
                    <td>{{ $feedback->category->name }}</td>
                    <td>{{ $feedback->vote_count }}</td>
                    <td>
                        <a href="{{ route('feedback.show', $feedback->id) }}" class="btn btn-info">View</a>
                        <a href="{{ route('feedback.edit', $feedback->id) }}" class="btn btn-warning">Edit</a>
                        <form action="{{ route('feedback.destroy', $feedback->id) }}" method="post" style="display:inline;">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this feedback?')">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    {{ $feedbacks->links() }}
</div>
@endsection

--}}

resources/views/feedback/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Feedback</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('feedbacks.index') }}"> Back </a>
            </div>
        </div>
    </div>

    <div class="row">
        {{-- @dd($feedback->comments) --}}
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $feedback->title }}
            </div>
            <div class="form-group">
                <strong>Description:</strong>
                {{ $feedback->description }}
            </div>
            <div class="form-group">
                {{-- <strong>Vote Count:</strong>
                {{ $feedback->vote_count }} 
                &nbsp;&nbsp;&nbsp;
                <a href="http://">Click Here</a> For Vote Add/Remove --}}
                {{-- @foreach($feedbacks as $feedback) --}}
                    <!-- Feedback item display... -->
                    <p>Vote Count: {{ $feedback->vote_count }}
                        <form action="{{ route('feedback.vote', $feedback->id) }}" method="post">
                            @csrf
                            <button type="submit" class="btn btn-primary">Vote</button>
                        </form>
                    </p>
                {{-- @endforeach --}}
            </div>
        </div>
            @if($feedback->comments_enabled)
            <h3 class="mt-5">Comments:</h3>
            @foreach($feedback->comments as $comment)
                {{-- @dd($comment) --}}
                <p><strong>{{ $comment->user->name }}:</strong><br>
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    {{ $comment->content }} <br>
                    <span class="publish">
                        Published {{ ($comment->created_at)->diffForHumans() }}
                    </span> 
                </p>
            @endforeach

            <hr>
            <h3>Add a Comment</h3>
            <form method="post" action="{{ route('comments.store', $feedback->id) }}">
                @csrf
                <div class="mb-3">
                    <label for="content" class="form-label">Comment</label>
                    <textarea class="form-control" id="content" name="content" rows="3" required></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Add Comment</button>
            </form>
            @endif
    </div>
@endsection

{{-- @section('content')
<div class="container">
    <h2>{{ $feedback->title }}</h2>
    <p><strong>Description:</strong> {{ $feedback->description }}</p>
    <p><strong>Category:</strong> {{ $feedback->category->name }}</p>
    <p><strong>Vote Count:</strong> {{ $feedback->vote_count }}</p>
    <hr>
    <h3>Comments</h3>
    @foreach($feedback->comments as $comment)
        <p><strong>{{ $comment->user->name }}:</strong> {{ $comment->content }}</p>
    @endforeach
</div>
@endsection --}}